export default {
  // active,
  // attention,
  // audible,
  // cookieStoreId,
  // discarded,
  // favIconUrl,
  // height,
  // hidden,
  // highlighted,
  // id,
  // incognito,
  // index,
  // isArticle,
  // isInReaderMode,
  // lastAccessed,
  // mutedInfo,
  // pinned,
  // sharingState,
  // status,
  // successorTabId,
  // title,
  // url,
  // width,
  // windowId
};
